### ISSUE TITLE
Docker compose file for HipChat

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#365]
The environment variables for HipChat are not bing pulled in for use with docker when setting up Cog using the HipChat adapter.

**Comment by lhaskins** [comment]
Add the HipChatconfig values to docker-compose.yml (along with the COG_ADAPTER variable)

**Comment by lhaskins** [comment]
### Motivation
We have a number of users who are attempting to use Cog with HipChat.  They are asking for the "quickest way to get started", preferably using Docker.

### Objective
The environment variables for HipChat are not bing pulled in for use with Docker when setting up Cog using the HipChat adapter. 

### Research
Ensure that setting the correct environment variables in docker.compose.yml for HipChat will work as expected. 

### Plan
Update the docker-compose.yml file to add in the HIPCHAT environment variables that pull the values from the local shell when performing `docker-compose up`

### Tasks
- [ ] Add the HipChat config values to docker-compose.yml (along with the COG_ADAPTER variable)
- [ ] Verify that docker setup for HipChat comes up and can communicate as expected
- [ ]  Verify that docker setup for Slack comes up and can communicate as expected

**Comment by mpeck** [comment]
So I think all of the info you need is here, but imo,  it may be a bit clearer if you reorganize a bit.

Motivation should include the clear problem statement. In this case users are trying to get cog running with HipChat using docker. You include that but I think it's also important to give some info as to why that is currently causing a problem. In this case it's because some environment variables aren't being set.

Objective should state what your intended actions will be to fix the problem. You basically have that info here, but it's implied not stated. Your research section actually states what you objective should be.

Research I think is somewhat optional based on the type of issue you are working on. I think this issue might be considered a bug so I don't know if a research section is even necessary. I would generally reserve research for feature additions or work that you aren't quite sure what the best path forward might be.

I think your plan is spot on. You identify areas of the code that you think will require changes and give a brief summary of work that needs to be done.

I may be being a bit pedantic. Like I said I think you have everything here, but the main purpose of this issue refinement process is to help the developer do the work and to help others understand what the planned work will be. It should make things easier to work on. This is also all just my opinion; I could be way off, so take what I say with a grain of salt. But overall :+1:
