### ISSUE TITLE
Embed permissions data in Role API

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#382]
Permission information should be included in the role API such that calls to 
`/v1/roles` and `/v1/roles/:id` (for consistency) return permissions data for each role in the format:
```
{
  "id" : "4eba6180-c467-490f-807e-3fd54e46cf1e",
  "name" : "superuser",
  "permissions" : {
    "operable": [
      {
        "id" : "af5f3403-f151-4f83-aafe-e7ccac810604",
        "name" : "manage_commands"
      },
      {
        "id" : "e79cc110-c5fa-4635-96a8-d95d55df11ea",
        "name" : "manage_permissions"
      },
      {
        "id" : "b78383ed-4632-430c-b518-3b8cee1d5ff3",
        "name" : "manage_roles"
      },
      {
        "id" : "1086addd-2492-472e-9af2-7e5526a864cc",
        "name" : "manage_users"
      }
    }
  }
}
```

**Comment by lhaskins** [comment]
### Motivation
Since roles is a collection of permissions, we should include the permissions that are associated with a particular role from the API.

### Objective
A single call to `/v1/roles` or `/v1/roles/:id` will return the role name, id, and permissions associated with the role.

### Research
#### What impact will this have in cogctl?
When listing roles, cogctl currently only lists the id and role name. If we want to list the permissions for each role, I recommend including a `roles info` call where the table layout would look like the following:
```
ID          123456789087654321
Name  MyRole

Permissions
NAMESPACE         NAME                                       ID
operable                    manage_commands         987654321234567890
operable                    manage_roles                      123456789098765432
site                                justForMe                              345678909876543210
```

The `roles` command can still just list the names and ids. We can leave it up to the `info` subcommand to display the permissions.

#### What does this mean concerning permissions and how they are displayed - for consistency?

####What else would need to possibly change?

### Plan
The Role model currently included the permissions, but does not return the permission data in the detail fields. This will need to change to include the permissions.

In the controller's `show` and `list` functions, we should change how the role is being rendered such that the output for each role reflects the following structure:
``` 
{
  "id" : "4eba6180-c467-490f-807e-3fd54e46cf1e",
  "name" : "superuser",
  "permissions" : {
    "operable": [
      {
        "id" : "af5f3403-f151-4f83-aafe-e7ccac810604",
        "name" : "manage_commands"
      },
      {
        "id" : "e79cc110-c5fa-4635-96a8-d95d55df11ea",
        "name" : "manage_permissions"
      },
      {
        "id" : "b78383ed-4632-430c-b518-3b8cee1d5ff3",
        "name" : "manage_roles"
      },
      {
        "id" : "1086addd-2492-472e-9af2-7e5526a864cc",
        "name" : "manage_users"
      }
    }
  }
}
```

### Tasks
- [ ] Add permissions to the detail_fields in the Role model.
- [ ] In the controller, for each permission we should render the associated namespace with each permission and permission id association.
- [ ] Add `roles info` to cogctl.

**Comment by mpeck** [comment]
Looks like a good write up to me @lhaskins :+1:

**Comment by imbriaco** [comment]
After living with this for a while, I've come to the conclusion that I gave you bad advice for the JSON format to return for roles. It makes sense in the micro-context of what you're likely to do with it if you're consuming that endpoint, but it has a major flaw: it makes us return permissions either inconsistently or in a way that does _not_ make sense for other contexts.

I think we're better off being consistent about what the JSON representation of a permission looks like, and that we should include the namespace in that shape, e.g.:
```
{
  "id" : "af5f3403-f151-4f83-aafe-e7ccac810604",
  "name" : "manage_commands",
  "namespace" : "operable"
}
```

For this specific controller, that means that we'd change the role index and show actions to return permissions as an array of those objects. This lets us (and API consumers) use the same code to marshall/unmarshall permissions in every context.

The example would look like this:

```
{
  "role": {
    "id" : "4eba6180-c467-490f-807e-3fd54e46cf1e",
    "name" : "superuser",
    "permissions" : [
      {
        "id" : "af5f3403-f151-4f83-aafe-e7ccac810604",
        "name" : "manage_commands",
        "namespace" : "operable"
      },
      {
        "id" : "e79cc110-c5fa-4635-96a8-d95d55df11ea",
        "name" : "manage_permissions",
        "namespace" : "operable"
      },
      {
        "id" : "20C0ADB8-118F-4789-8049-4ED989098244"
        "name" : "my_permission",
        "namespace" : "site"
      }
      {
        "id" : "b78383ed-4632-430c-b518-3b8cee1d5ff3",
        "name" : "manage_roles",
        "namespace" : "operable"
      },
      {
        "id" : "1086addd-2492-472e-9af2-7e5526a864cc",
        "name" : "manage_users",
        "namespace" : "operable"
      }
    ]
  }
}
```

Let me know if that doesn't make sense. A similar philosophy to this should be used for the other API responses where we embed child objects such that we're consistent about the JSON representation in all cases to the maximum extent possible.

**Comment by imbriaco** [comment]
One other thing I forgot to mention that was bothering me about this, despite the fact that I suggested it, was having a key named "permissions" that was not an array of permission objects. That was design smell from the beginning.
