### ISSUE TITLE
Add the groups of a user

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#474]
The User model should include the group membership information when performing a show in the API

**Comment by lhaskins** [comment]
### Motivation
Returning group membership information gives additional information using a single call instead of multiple calls when this information will be used the majority of the time when retrieving user information through the API.

### Objective
When performing a GET for User information, we should return group membership information as well.

### Research
Preload group_membership when performing a show. Should this be done for index as well?

### Plan
Preload group memberships when performing show and list for users.

### Tasks
- [ ] Preload membership info into User structure.
- [ ] Move to use view instead of EctoJson.
- [ ] Update/add tests.
- [ ] Update/add documentation.
