### ISSUE TITLE
Add commands in a bundle to API

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#476]
The list of available commands in a bundle should be available in the bundle API call.

**Comment by lhaskins** [comment]
### Motivation
When displaying information about a bundle, it is useful to see what commands are available in the bundle.

### Objective
When performing bundles#show or bundes#index, we should return the list of commands in a specified bundle.

### Plan
Preload the commands into the bundles when performing bundles#index or bundles#show. 

Currently, the commands are present when a #show is executed, but not when a #index is executed.

Returning structure will look like the following:
```
%{"id" => "some-id",
  "name" => "some-group",
  "commands" => [%{"id" => "command-id",
                   "name" => "some-command-name"},
                 %{"id" => "other-command-id",
                   "name" => "some-other-command-ame"}]
}
```
The use of EctoJson will no longer be used in this controller.

The cogctl tool will not need to be updated to display the commands that are in a bundle as this information is already present in the output for the bundles info call.

### Tasks
- [ ] Preload commands into Bundle structure.
- [ ]  Move to use view instead of EctoJson.
- [ ] Update/add tests.

**Comment by vanstee** [comment]
This has been done as part of flywheel api work.
