### ISSUE TITLE
Relay & Command Bundles 2.0

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#477]
## Motivation
Cog's current design wrt Relay and command bundles was good enough for our initial uses. As Cog has gotten wider use it's becoming clear we need to re-think both Relay and command bundle structure for at least the following reasons:

1. Defining and maintaining a bundle file format has turned into a distraction from the core problems we're trying to solve w/Cog. Other projects, like Docker, have done a much better job of defining a packaging format and have significantly greater mindshare.
1. Our current execution model provides some level of isolation between command invocations. Commands cannot see each other's execution environments but that's where our notion of isolation ends. Adopting current state of the art technology, such as Linux containers or BSD jails, would significantly increase isolation between command invocations and strengthen the security guarantees Cog can offer.
1. There's been a lot of interest in using Relays as executors pervasively deployed throughout an environment. This is significantly different from the uses cases informing Relay's original design. Using Relays in this way makes a lot of sense from both a technical and operational point of view. Relay's current design and the way it interacts w/Cog makes supporting this type of use awkward.

## Plan
Addressing the above points by iteratively improving Relay is possible but would take several man-weeks to execute. Even then we'd still have concerns with Relay's deployment footprint and setup experience since it would still be written in Elixir and thus bring non-trivial runtime requirements.

The best way forward is to aggressively reimplement Relay now while we still have the flexibility to make significant non-backwards compatible changes. At a high level the plan is as follows:

* Reimplement Relay in Go (single executable + config file deployment)
* Replace standard (zip file) bundles with Docker container images
* Continue to support simple bundle execution as currently provided
* Replace standard bundle command execution with Docker containers
* Place Cog in the driver's seat wrt authorizing and enabling new Relay hosts
* Allow users to group Relays into named groups
* Deploy bundles onto named Relay groups

## Tasks
- [x] Research Go MQTT and Docker client libs
- [x] Figure out how to invoke a Docker container
  - [x] Intercept stdout, stderr
  - [x] Send input over stdin
- [x] Implement Relay API
  - [x] Relay data model & migrations
  - [x] Relay CRUD REST API
  - [x] Relay group data model & migrations
  - [x] Relay group CRUD REST API
  - [x] cogctl support for above APIs
- [x] Rework Relay registration process
  - [x] Shared secret authentication
  - [x] Explicit enabled flag per-Relay
  - [x] Integrate w/emqttd's authentication and authorization subsystems
- [x] Rework bundle deployment process
  - [x] Bundle deployment descriptor support for containers
  - [x] Push deploys Cog -> Relays
  - [x] Simple bundles
  - [x] Container bundles
  - [x] cogctl support
- [x] Relay 2.0 (aka `go-relay`)

**Comment by zeisss** [comment]
Will the usage of Docker be optional? I would find it sad for docker to become a hard requirement for a bunch of reasons:
* This would make it harder to run a relay in a docker container. I would have to use docker-in-docker, more operations overhead and use privileged containers. 
* Docker seems to be the current leader of the container market, but thats not set in stone. Maybe someone prefer rkt or lxc containers.
* Docker IMO is regularly unstable and fails in horrible ways. Using it in the last 2 years for me has be a box of surprises.

Generally I don't see the need for this really (if I understand the idea here correctly). If an organizations wants more isolation between bundles, can't they just put each bundle in it's own relay?

**Comment by kevsmith** [comment]
@zeisss Thanks for the questions. The answers given below represent current development status as of Apr 4 2016.

* Relay uses a self-contained Docker client library and, thus, only requires access to the Docker socket so it pull images and run containers. Bind mounting the socket into the Relay container provides the required access and avoids docker-in-docker shenanigans.

* Relay's use of Docker is intended to be modular just so we can eventually support multiple execution strategies. The new Relay will support 2 "out of the box": Docker containers and native processes. [Simple bundles](https://github.com/operable/cog/wiki/Building-Command-Bundles#simple-bundles) are the easiest type of command to author and execute directly on the Relay host. Supporting simple bundles requires Relay to be able to execute non-containerized commands. If we get the design right Relay should be able to support multiple command execution strategies including Docker, rkt, VMs, native processes, etc.

We think replacing bundle files with support for other packaging alternatives makes sense for a few reasons:

1. Some packaging formats are already ubiquitous and deeply integrated into current practices. These formats include operating system packages like `.deb` and `.rpm` and programming language formats like `npm`. Simple bundles could be easily packaged using these formats.
1. Package distribution, verification, and installation is largely a solved problem for the above package types. Using these common package types also permits reusing deployment infrastructure which is likely to exist in most environments. Here we're thinking of systems like Chef, Ansible, Puppet, etc.
1. The popularity of containers as a packaging and deployment format has exploded in the past 2 years. Since launching Cog we've received several requests for Docker support. We believe we can provide support for containers without harming the experience for users and teams not using containers.
1. We're a small team and need to be careful about how and where we spend our time. We care deeply about advancing ChatOps state of the art along a number of axes including security, ease of use, power, and expressiveness. Defining and maintaining another packaging format, especially when so many good ones already exist, is a distraction from our core mission.

**Comment by zeisss** [comment]
This all sounds good, thanks for the detailed response. I am looking forward to 0.4 then :)

**Comment by imbriaco** [comment]
Work in progress sneak peek:

```
ksmith@relay2$ docker images | grep operable/docker-base

ksmith@relay2$ RELAY_ID="49df1b14-b339-487a-87af-09cab4eca307" RELAY_COG_HOST=10.10.2.12 ./cog-relay
INFO[2016-04-05T15:11:10-04:00] Configuration file /etc/cog_relay.conf loaded.
INFO[2016-04-05T15:11:10-04:00] Relay 49df1b14-b339-487a-87af-09cab4eca307 is initializing.
INFO[2016-04-05T15:11:10-04:00] No Docker registry credentials found. Skipping auth check.
INFO[2016-04-05T15:11:10-04:00] Docker configuration verified.
INFO[2016-04-05T15:11:10-04:00] Started 8 workers.
INFO[2016-04-05T15:11:10-04:00] Connected to Cog host 10.10.2.12.
INFO[2016-04-05T15:11:11-04:00] Requested latest command bundle assignments.
INFO[2016-04-05T15:11:11-04:00] Relay 49df1b14-b339-487a-87af-09cab4eca307 is ready.
INFO[2016-04-05T15:11:11-04:00] Downloading Docker image operable/docker-base::latest for bundle test_bundle.
INFO[2016-04-05T15:12:20-04:00] Downloaded Docker image operable/docker-base::latest for bundle test_bundle.
^C
INFO[2016-04-05T15:12:25-04:00] Starting shut down.
INFO[2016-04-05T15:12:25-04:00] Relay 49df1b14-b339-487a-87af-09cab4eca307 shut down complete.

ksmith@relay2$ docker images | grep operable/docker-base
operable/docker-base   latest              618d75ce1ac5        3 weeks ago         646.9 MB
```
