### ISSUE TITLE
Manage relays and relay groups in cogctl

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#487]
Add support for the new Relay and RelayGroup endpoints to `cogctl`.

**Comment by lhaskins** [comment]
### Motivation/Objective
There are no commands in cogctl that allow for the viewing or manipulation of relays for Cog. The ability to perform the following must be added:

#### Relays
* relay#index (a list of all relay names, ids, and creation times of relays for the Cog instance)
* relay#create (allows for the creation of a relay with the specified name  and token - Choose wisely. The relay name is currently immutable.)
* relay#show (show the details of a specific relay to include: name, id, creation time, status, description, and group association)
* relay#delete (deletes a particular relay and if it is the last relay in a group, deletes the corresponding group)
* relay#enable (enables a relay)
* relay#disable (disables a relay)
* relay#update (allows for the updating of the name and description of a relay)

#### Relay Groups
* relay_groups#index (a list of all relay groups containing: group names, ids, and creation times for the Cog instance)
* relay_groups#create (all for the creation of a relay group with a specified name)
* relay_groups#show (shows the details of a relay group to include: group name, id, creation time, associated bundles and associated relays. The bundles and relays should list names and IDs.)
* relay_groups#update (updates the group that the relay is associated with)
* relay_groups#delete (deletes a relay group. This should verify that there are no associated relays in the group before the group is deleted.)
* relay_groups#add (Adds a relay to a relay group)
* relay_groups#remove (Removes a relay from a relay group (If it is the last relay in the group, the relay group should be deleted.) 
* relay_groups#assign (Assigns a bundle to a relay group)
* relay_groups#retract (Retracts a bundle from a relay group)

### Research/Questions
Should the relay group be deleted when the last relay is deleted? Should we display a message that states that there are no more relays in the group upon the deletion of the last relay from that group?

### Plan
The results from the command `cogctl relays` should display in the following format:
```
NAME          STATUS       CREATED                   ID
test-relay    enabled      2016-04-05T16:00:00Z      123456
my-relay      enabled      2016-04-01T08:02:18Z      987654
```

The results from the command `cogctl relays create --name=my-relay --token=special_token` should display the following:
```
Create relay named my-relay.
```

The results from the command `cogctl relays update --description="This is a description of my relay" my-relay` should display the following:
```
Updated relay named my-relay.

ID              24680
Name            my-relay
Creation Time   2016-04-01T08:02:18Z
Status          enabled
Description     This is a description of my relay

Relay Groups
NAME               ID
relay-group        09876
```

### Tasks
- [ ] CogCtl: Update optparse to include the new Relay modules.
- [ ] CogCtl: Add new relay modules for each command.
- [ ] CogCtl: Update display_error to handle list of errors.
- [ ] Cog: Add description to relay view.
- [ ] Cog: Update Relay Model to use `description` instead of `desc`
- [ ] CogAPI: add the token as a parameter in the relay#create endpoint.
- [ ] Update/add tests.
- [ ] Update/add documentation.
