### ISSUE TITLE
Allow a user to update their own user information

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#489]
A user should be able to update their own information without having the manage_users permission.

**Comment by lhaskins** [comment]
### Motivation/Objective
A user should be able to update their own user information regardless of permissions.

### Research
Instead of updating in the authorization plug to check for the method and the data, have an intermediate plug that will determine if authorization is needed in the first place. 

This will allow for an isolation of this change such that it stays in the User controller and the authorization isn't called if it isn't necessary.

I'm not sure if I am able to use certain functions in a guard such that I can access the connection that is used in the plug. 

The plug updates the connection data.

### Plan
Since what I can do in a guard function is limited in accessing the connection map, I need to perform much of the logic in a separate plug and then update the plug only if it is the same user updating their own information. 

### Tasks
- [ ] Write new plug method.
- [ ] Write new guard macro for use when determining whether to authenticate the execution of the command.
- [ ] Update/add tests.
- [ ] Update/add documentation.
