### ISSUE TITLE
Manage relay groups in cogctl

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#506]
Add support for the new RelayGroup endpoints to cogctl.

**Comment by lhaskins** [comment]
### Motivation/Objective
There are no commands in cogctl that allow for the viewing or manipulation of relay groups for Cog. The ability to perform the following must be added:

#### Relay Groups
* relay_groups#index (a list of all relay groups containing: group names, ids, and creation times for the Cog instance)
* relay_groups#create (all for the creation of a relay group with a specified name)
* relay_groups#show (shows the details of a relay group to include: group name, id, creation time, associated bundles and associated relays. The bundles and relays should list names and IDs.)
* relay_groups#update (updates the group that the relay is associated with)
* relay_groups#delete (deletes a relay group. This should verify that there are no associated relays in the group before the group is deleted.)
* relay_groups#add (Adds a relay to a relay group)
* relay_groups#remove (Removes a relay from a relay group (If it is the last relay in the group, the relay group should be deleted.) 
* relay_groups#assign (Assigns a bundle to a relay group)
* relay_groups#retract (Retracts a bundle from a relay group)

### Research/Questions
Should the relay group be deleted when the last relay is deleted? Should we display a message that states that there are no more relays in the group upon the deletion of the last relay from that group?

### Plan
The results from the command `cogctl relay-groups` should display in the following format:
```
NAME          CREATED                   ID
test-relays    2016-04-05T16:00:00Z      123456
my-relays      2016-04-01T08:02:18Z      987654
```

The results from the command `cogctl relay-groups create --name=my-relays` should display the following:
```
Created relay group named my-relays.
```

The only thing that could be updated using the update command would be `name`, but since relay groups will be used in rules, updating the name could cause some issues if the name changes don't cascade to the rules as well. As a result, a cogctl update command is not necessary.

The results from the command `cogctl relay-groups info  my-relays` should display the following:
```
ID              24680
Name            my-relays
Creation Time   2016-04-01T08:02:18Z

Relays
NAME               ID
relay1        09876

Bundles
NAME               ID
my-bundle        09876
```

The results from the command `cogctl relay-groups add --relay=relay1 my-relays` should display the following:
```
Relay relay1 added to relay group my-relays
```

The results from the command `cogctl relay-groups remove --relay=relay1 my-relays` should display the following:
```
Relay relay1 removed from relay group my-relays
```

The results from the command `cogctl relay-groups assign --bundle=my-bundle my-relays` should display the following:
```
Bundle my-bundle has been assigned to relay group my-relays
```

The results from the command `cogctl relay-groups retract --bundle=my-bundle my-relays` should display the following:
```
Bundle my-bundle has been removed from relay group my-relays
```

### Tasks
- [ ] CogCtl: Update optparse to include the new RelayGroups modules.
- [ ] CogCtl: Add new relay groups modules for relay_groups#index.
- [ ] CogCtl: Add new relay groups modules for relay_groups#create
- [ ] CogCtl: Add new relay groups modules for relay_groups#info
- [ ] CogCtl: Add new relay groups modules for relay_groups#add
- [ ] CogCtl: Add new relay groups modules for relay_groups#remove
- [ ] CogCtl: Add new relay groups modules for relay_groups#assign
- [ ] CogCtl: Add new relay groups modules for relay_groups#retract
- [ ] CogCtl: Add new relay groups modules for relay_groups#delete
- [ ] Cog: .
- [ ] CogAPI: The relay_groups#show command should also be able to take a relay name
- [ ] CogAPI: The relay_groups#update command should also be able to take a relay name
- [ ] CogAPI: The relay_groups#delete command should also be able to take a relay name
- [ ] CogAPI: .
- [ ] Update/add tests.
- [ ] Update/add documentation.

**Comment by imbriaco** [comment]
Good questions. Here are my thoughts:

1. Do not delete the relay group when the last relay is deleted, but do include a note that says that the relay group does not contain any relays.
2. I'd like to remove the `--name` option in `cogctl relay-groups create` and expect it as the first argument after create instead, e.g. `cogctl relay-groups create <name>`. This way reads much better to me. Same for `cogctl relay-groups delete <name>`.
3. 👍  `cogctl relay-groups [add|remove] my_group --relay my_relay`
4. 👍  `cogctl relay-groups assign my_group --bundle my_bundle`
5. I'd prefer to use `unassign` instead `retract`.
