### ISSUE TITLE
Roles in User endpoint

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#514]
The Cog API should return the roles of a user

**Comment by lhaskins** [comment]
### Motivation/Objective
We need to view the roles (and permissions with those roles) for a user.

### Research
We should preload the roles for a user. There are lots of extra details in the user model that are not being used at this moment. Any references outside of the model can be removed.

### Plan
Preload the roles in the User controller. Be sure that the view pulls in and formats the output with all the necessary info.

### Tasks
- [ ] Cog: Update Controller to include preloads.
- [ ] Cog: Update Controller to accept name instead of id for #show.
- [ ] CogAPI: Update to take a name as well as an id
- [ ] CogCtl: Update commands to use API calls.
- [ ] CogCtl: Update #info to show associated roles.
- [ ] Update/add tests.
- [ ] Update/add documentation.
