### ISSUE TITLE
Add groups to the roles API endpoint

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#525]

**Comment by lhaskins** [comment]
### Motivation/Objective
We need to view the groups that are associated with a role.

### Research
We should preload the groups associated with a role. There are lots of extra details in the user model that are not being used at this moment. Any references outside of the model can be removed.

There is definitely a potential to end up in a data loop between roles and groups, so care has to be taken to build these structures separately.

### Plan
Preload the groups in the Role controller. Be sure that the view pulls in and formats the output with all the necessary info.
The JSON format of the response will look like:
```
%{"id" => "12345678",
  "name" => "take-over",
  "groups" => [%{"id" => "98765432",
                 "name" => "robots"}],
  "permissions" => [%{"id" => "876543",
                      "name" => "world",
                      "namespace" => "site"}]
  }
```
The `roles info` command should return groups such that the output looks like the following:
```
NAME       ID
take-over  12345678

Permissions:
NAMESPACE  NAME   ID
site       world  876543

Groups:
NAME      ID
robots    98765432
```

### Tasks
- [ ] Cog: Update Controller to include preloads.
- [ ] Cog: Update Controller to accept name instead of id for #show.
- [ ] CogAPI: Update to take a name as well as an id
- [ ] CogAPI: Update the User resource to include roles
- [ ] CogCtl: Update commands to use Client API calls (instead of Internal)(delete and update).
- [ ] CogCtl: Update #info to show associated groupss.
- [ ] Update/add tests.
- [ ] Update/add documentation.

**Comment by imbriaco** [comment]
This looks good.
