### ISSUE TITLE
Working with relays and relay groups is awkward

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#535]
Creating relays and relay groups and modifying relay group memberships is awkward because we require too many discrete steps. It should be possible to do the following via `cogctl`:

* Create a relay and assign it to one or more groups in a single invocation

`cogctl relays create test1 --token sekrit --groups test1,test2`

* Create a relay group and assign one or more members in a single invocation

`cogctl relay-groups create test1 --members relay1,relay2,relay3`

**Comment by lhaskins** [comment]
### Motivation/Objective
We want to reduce the number of steps needed in order to organize relays into different groups.

### Research
What option types are available for cogctl? May need to add a list option type.

### Plan
Add a new `groups` option and make the type list, such that it is parsed for me upon converting the parameters from the options list.

Then after creating the relay and verifying that each group in the list exists, assign the relay to the listed groups.

The output of the `cogctl relays create relay-test --token sekrit --groups relaygroup1,relaygroup2, grou3` command would look like the following:
```
Created relay-test

ID    12246789
Name  relay-test

Relay `relay-test` added to relay group `relaygroup1`
ERROR: Unable to add `relay-test` to `relaygroup2`: Resource not found
Relay `relay-test` added to relay group `group3`
```

### Tasks
- [ ] CogAPI: Error message for missing relay group.
- [ ] Cogctl: allow the optional groups option.
- [ ] Cogctl: If groups are present in the param list, add the relay to the listed group(s).
- [ ] Update/add tests.
- [ ] Update/add documentation.

**Comment by kevsmith** [comment]
Output need some polishing. Here's an example where I tried to create & add a relay to a list of relay groups, some of which didn't exist:

```
$ cogctl relays create --token sekrit test1 --groups test1,test2,test-group1
Created test1

ID    9d2e35c9-66fe-40f7-9770-239a897e4874
Name  test1

Unable to add relay `test1` to relay group `test1`: Resource not found for: 'relay_groups'
Unable to add relay `test1` to relay group `test2`: Resource not found for: 'relay_groups'
Relay `test1` added to relay group `test-group1`
Error: 2
```

**Comment by lhaskins** [comment]
So to be sure, are you saying that you would prefer to see the following:
```
Created test1

ID    9d2e35c9-66fe-40f7-9770-239a897e4874
Name  test1

ERROR: Unable to add `test1` to `test1`: Resource not found for: 'relay_groups'
ERROR: Unable to add `test1` to `test2`: Resource not found for: 'relay_groups'
Relay `test1` added to relay group `test-group1`
Error: 2
```

**Comment by kevsmith** [comment]
Summarizing chat conversation regarding output formatting. Output should look something like:

```
$ cogctl relay-groups create --token sekrit test1 --groups test1,test2,test-group1
ID     9d2e35c9-66fe-40f7-9770-239a897e4874
Name   test1

Adding 'test1' to relay group 'test1': Error. Relay group not found.
Adding 'test1' to relay group 'test2': Error. Relay group not found.
Adding 'test1' to relay group 'test-group1': Ok.
```

And status codes (process exit codes) should not be included in output since they're available from the shell and programming language runtimes/libraries.
