### ISSUE TITLE
Remove the "Create <resource>" line

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#546]
In cogctl, we state the we have created a specific resource and then supply the ID and other information concerning the created resource.

It's redundant to display this message. We can remove the "Created <resource>" line from the output displayed.

**Comment by vanstee** [comment]
In some commands we use those lines to display actions that happened during the command for instance that aren't necessarily clear. Running `cogctl relays create test-relay --enable --relay-groups=default-group` prints something like the following before returning.

```
Created test-relay
Enabled test-relay
Added test-relay to default-group
```

Do we want to explain those actions anywhere? I kinda considered the details as the extra content for these commands rather than the actions themselves. If the variable number of action lines are causing issues for parsing I'd recommend that we don't include the detail view and tell users to always run the `cogctl relays info` style command after `cogctl relays create` exited successfully.

**Comment by lhaskins** [comment]
My thinking is that the results of such a command would be more along the lines of
```
ID             12345678
Name           test-relay
Status         enabled
Relay Groups   default-group
```

If the `enable` flag or `relay-groups` list is not included, then that information doesn't get displayed - only the Name and ID.

This way the user can still see the results of the command without the additional command execution.

**Comment by vanstee** [comment]
Cool. I think that'll work.

**Comment by lhaskins** [comment]
### Motivation/Objective
All output for the commands should be consistent and useful. We should continue to make our commands easy for use in scripts and pipelines.

### Research
There are a few commands (chat handles, rules) that have not been converting over to using the "new" CogApi" endpoints. These should be converted over, if possible. (Don't want to jump the gun, if work has not been completed. Completion of that work should be in a separate PR that may or may not be apart of this issue.)

There are also some commands that currently only display that a task has been completed. It is more useful to display the ID and Name of what is being completed. For example, as stated in previous comments in this issue, given the command `cogctl relays create test-relay --enable --relay-groups=my-group,default-group` the result should be
```
ID             12345678
Name           test-relay
Status         enabled
Relay Groups   default-group, my-group
```
It should be noted, as stated above, if the `enable` flag or `relay-groups` flag (actual flag is `groups`) is not present, the corresponding information would not be included. Note that the groups listed will be sorted in alphabetical order.

The relay-group, role, and permission create commands will follow suite.

### Plan
During the endeavor to clean up cogctl for ease of maintenance and readability, a util.ex file will be added for each command, if one does not exist. This allows for more consistent output display during the course of the command execution.

Ideally, the object should be passed to a render function that displays the output according to the resource data needed.

### Tasks
- [ ] Add util.ex files and clean up existing to use render function call .
- [ ]  Be sure that the functions all return either :error or :ok
- [ ] Change calling functions to accept objects and leave it up to render to display the correct information in the desired format.
- [ ] Update/add tests.
- [ ] Update/add documentation.

**Comment by mpeck** [comment]
This sounds reasonable to me, but I'm wondering if we should break it up a bit more. I think it might be useful to do one resource at a time. That should keep the PRs relatively small and help review move more quickly. It also means that we can break things up between multiple people if need be, and not worry about getting in each others way.

I'm not 100% sure what the best way to note that here would be though. Maybe a list of resources as tasks and then include the list you have here for each resource PR, just to help make sure that we don't miss anything.

**Comment by mpeck** [comment]
@lhaskins I actually meant just to include the list of resources here. Then have a short checklist of things for each command on their respective PRs. I think it might be easier to grok like that. I also think we should include test updates per resource.

**Comment by kevsmith** [comment]
Summarizing conversation between @mpeck and myself:

1. This ticket will remain scoped to fixing the issue described in the title.
1. All tasks not directly related to removing "Created ..." from command output are going to be moved to a separate ticket concerned with fixing a wider array of cogctl issues. The ticket will include a high level sumary of proposed work and a level of effort estimate.
1. We (@mpeck, @lhaskins, myself) will discuss the new ticket at 1:30 PM EDT today. Questions we need to answer during the discussion include:

* Is the proposed set of tasks reasonably sized or should they be further decomposed? If further decomposition is necessary, what logical subset of tasks fits into 0.5's and 0.6's work windows?
* Does work of this scope make sense at all given our previously stated desire to re-implement `cogctl` is a simpler to deploy language like Go?

For future reference, expanding the scope of a ticket this far (24+ tasks) without discussion and feedback is the complete opposite of release philosophy discussed yesterday during the team roadmap call -- "Flex scope not the date".

**Comment by kevsmith** [comment]
👍
