### ISSUE TITLE
Add `--enable` flag to `cogctl relays create`

### ISSUE THREAD

**Issue by vanstee** [operable/cog#566]
We should add an `--enable` flag to the `cogctl relays create` command to more easily create and enable a relay in one command. This is similar to how `cogctl bundles create --enable` works currently.

**Comment by lhaskins** [comment]
The output should look like the following:
```
ID             12345678
Name           test-relay
Status         enabled
Relay Groups   default-group
```

If the `enable` flag or `relay-groups` list is not included, then that information doesn't get displayed - only the Name and ID.

**Comment by lhaskins** [comment]
### Motivation/Objective
Adding the enable flag eliminates the added step of enabling the created relay. If the flag is supplied, we should enable the relay upon successful creation.

### Research/Plan
There will be an added boolean option `enable` with a default value set to `false`. If the command uses the flag i.e. `cogctl relays create test-relay --enable`, then the resulting output would be:
```
ID             12345678
Name           test-relay
Status         enabled
```
If no flag is passed, the resulting output will still display the status so that it will be clear to the user that the relay is disabled. This would help reduce any confusion concerning the state of the relay. i.e. given the command `cogctl relays create test-relay` the following would be the output:
```
ID             12345678
Name           test-relay
Status         disabled
```

### Tasks
- [ ] Add the enable flag option.
- [ ]  Add the call to enable the relay
- [ ] Add the display of the information to the output.
- [ ] Update/add tests.
- [ ] Update/add documentation.

**Comment by kevsmith** [comment]
Looks good.
