### ISSUE TITLE
Separate rendering logic

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#580]
### Motivation
The cogctl command output is not always consist between resources and actions. There are also numerous places in cogctl where the rendering logic is intertwined with the command logic. Separating the rendering logic out from the action logic and having it reside in a single location for each resource would be beneficial for readability and maintainability. 

### Objective
Once this change is made, it should be very simple to update the way the output from different commands are displayed. The action logic modules should also be easier to follow when it comes to what is happening to perform the specified command.

### Research
Many commands combine logic to request data with the logic to present said data. This makes it difficult to share rendering logic between similar commands and creates a lot of additional work when out for a particular type needs to change. With this refactor we plan on moving all rendering bits into a separate module that can be shared between commands.

### Plan
Each command should call a `render` function. Ideally, this `render` function would reside in a View module that allows for both `render` and optionally a `render_resource` that can be used when listing a list of named resources. For example, `GroupView.render` would return a table containing the group ID and group Name; where `GroupView.render_resource` would return a row for entry into a table that contains a list of group names. This allows for consistent display and reuse across many different resources and the information that is to be displayed. As input the render functions will expect the resource structure.

There will be multiple PRs that cover this work, potentially a separate PR for each resource depending on the current state of the resource action modules. There may be situations where multiple resources can fit into a single PR. 

### Questions
1. When displaying the results of delete, is `Deleted <resource> <resource_name>` sufficient? Or would you prefer something else?

### Tasks
The following is a list of potential PR separations. Also in many of these resources, most of the work has already been done.

For each resource the following would be done:
* Add the View module
* Call the render function from the different command logic
* Update tests and documentation as needed

- [ ] Bundles
- [x] Permissions & Chat-handles 
- [ ]  Roles & Users & Groups
- [ ] Relay Groups & Relays
- [ ] Rules
- [ ] Triggers

**Comment by kevsmith** [comment]
The motivation, research, and plan sections are good. Tasks are much too fine grained. iirc, we'd agreed each checkbox item would represent a logical grouping of work submitted in a single PR. Based on our conversation earlier today, I'd had the impression it'd look something like this:

--- -

Refactor tasks to be performed on each group of actions listed below:

* Implement view module(s)
* Add `render` calls in each action to render views
* Update tests and documentation as needed

Each of the following groups will be submitted as a single PR to simplify review and facilitate quick progress:

- [ ] Bundles
- [ ] Chat-handles & Permissions
- [ ] Groups

etc, etc, etc
--- -

**Comment by kevsmith** [comment]
👍
