### ISSUE TITLE
Create a stand-alone Greenbar app

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#952]
While it is easy to test Greenbar templates for the embedded `operable` bundle, it is currently not possible (or, at least, really hard!) to similarly test templates for external bundles.

To help with this, we should provide a stand-alone Greenbar application (either an all-encompassing escript, a Docker container, or something else). This could be incorporated into bundle testing procedures, allowing bundle authors to be confident that their templates compile. With a basic directive processor included, they could also see a version of the final rendered output (as testing directly against Greenbar directives is a bit low-level).

**Comment by kevsmith** [comment]
## gbexec

Tool providing offline template execution and testing.

### Docs

`gbexec <template_file> [<json_file>|-] (-s,--slack|-c, --hipchat)`

When `<json_file>` is `-` then gbexec will read input JSON from stdin.

#### Options

1. `-s`, `--slack` Render template output into Slack's Markdown-based format
1. `-c`, `--hipchat` Render template output into HipChat's HTML-based format

### Examples

`gbexec templates/users.greenbar /tmp/users.json -s`
`cat /tmp/demo_data.json | gbexec templates/vms.greenbar - -c`

### Implementation notes

* Build as an escript packaged app for simplicity and dev speed
* gbexec should reuse the HipChat and Slack provider's `TemplateProcessor`s.
* Probably worth investigating how we could extract those providers into separate OTP apps to facilitate easy reuse.

**Comment by kevsmith** [comment]
## Tasks

- [ ] Extract template processors into separate library
- [ ] `gbexec` app skeleton
- [ ] Add Slack template support to `gbexec`
- [ ] Add HipChat template support to `gbexec`

**Comment by kevsmith** [comment]
See [gbexec](https://github.com/operable/gbexec)
